name: Auto Publish to NPM

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
      - 'docs/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CONTRIBUTING.md'
      - 'INSTALLATION.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Lint
        run: npm run lint
        
      - name: Build
        run: npm run build
        
      - name: Run tests
        run: npm run test:production-ready

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build:clean
        
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
      - name: Auto-bump version based on commit
        id: version_bump
        run: |
          # Skip version bump if this is already a version bump commit
          if git log -1 --pretty=%B | grep -q "chore: bump version"; then
            echo "Skipping version bump - this is already a version bump commit"
            echo "skip_publish=true" >> $GITHUB_OUTPUT
          else
            node scripts/bump-version.js
            NEW_VERSION=$(node -p "require('./package.json').version")
            echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
            echo "skip_publish=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Commit and push version bump
        if: steps.version_bump.outputs.skip_publish == 'false'
        run: |
          git push origin main
          
      - name: Publish to NPM
        if: steps.version_bump.outputs.skip_publish == 'false'
        run: |
          echo "Publishing version ${{ steps.version_bump.outputs.new_version }} to NPM"
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Create release tag
        if: steps.version_bump.outputs.skip_publish == 'false'
        run: |
          git tag "v${{ steps.version_bump.outputs.new_version }}"
          git push origin "v${{ steps.version_bump.outputs.new_version }}"
