name: Comprehensive Testing Strategy

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  user-journey-tests:
    name: User Journey Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Run User Journey Tests
        run: npm run test:user-journey
        env:
          CI: true

  performance-baselines:
    name: Performance Baseline Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Run Performance Baseline Tests
        run: npm run test:performance-baselines
        env:
          CI: true

  cross-platform-tests:
    name: Cross-Platform Compatibility
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16, 18, 20]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Run Compatibility Tests
        run: npm run test:compatibility
        env:
          CI: true

  feature-tests:
    name: Comprehensive Feature Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Run Feature Tests
        run: npm run test:features-comprehensive
        env:
          CI: true

  production-readiness:
    name: Production Readiness
    runs-on: ubuntu-latest
    needs: [user-journey-tests, performance-baselines, cross-platform-tests, feature-tests]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Run Production Tests
        run: npm run test:production
        env:
          CI: true
      - name: Validate Package
        run: npm pack --dry-run
