name: JSON Session Analytics Automation

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      analytics_type:
        description: 'Type of analytics to generate'
        required: false
        default: 'comprehensive'
        type: choice
        options:
          - comprehensive
          - productivity
          - trends
          - predictive

jobs:
  generate-analytics:
    runs-on: ubuntu-latest
    name: Generate JSON Session Analytics
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'docs/package.json'
          
      - name: Install Dependencies
        run: |
          cd docs
          npm install
          
      - name: Generate Comprehensive Analytics
        run: |
          cd docs
          node scripts/advanced-analytics.js report
          
      - name: Generate Productivity Insights
        run: |
          cd docs
          npm run json:analytics > analysis/productivity-summary.txt
          
      - name: Check for Anomalies
        run: |
          cd docs
          node scripts/anomaly-detection.js
          
      - name: Update README Badges
        run: |
          cd docs
          node scripts/update-readme-badges.js
          
      - name: Commit Analytics Updates
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if [ -n "$(git diff --name-only)" ]; then
            git add docs/analysis/
            git add docs/README.md
            git commit -m "chore: update session analytics [automated]
            
            📊 Analytics Update:
            - Generated comprehensive analytics report
            - Updated productivity metrics
            - Checked for data anomalies
            - Updated documentation badges
            
            Generated by: JSON Session Analytics Automation"
            git push
          else
            echo "No changes to commit"
          fi
          
      - name: Create Issue for Anomalies
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Session Analytics Anomaly Detected',
              body: `## Analytics Anomaly Alert
              
              The automated session analytics detected an anomaly in the data.
              
              **Timestamp**: ${new Date().toISOString()}
              **Workflow**: ${context.workflow}
              **Run ID**: ${context.runId}
              
              Please review the analytics reports and investigate:
              1. Check recent session entries for data quality issues
              2. Verify JSON schema compliance
              3. Review analytics logs for specific errors
              
              [View Workflow Run](${context.payload.repository.html_url}/actions/runs/${context.runId})
              `,
              labels: ['analytics', 'automation', 'investigation-needed']
            });
