name: CSV to JSON Migration Monitor

on:
  push:
    paths:
      - 'docs/SESSIONS.csv'
  workflow_dispatch:

jobs:
  monitor-migration:
    runs-on: ubuntu-latest
    name: Monitor and Sync CSV to JSON
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'docs/package.json'
          
      - name: Install Dependencies
        run: |
          cd docs
          npm install
          
      - name: Check Migration Status
        id: migration_check
        run: |
          cd docs
          
          # Count entries in both formats
          CSV_COUNT=$(tail -n +2 SESSIONS.csv | wc -l)
          JSON_COUNT=$(node -e "console.log(JSON.parse(require('fs').readFileSync('sessions.json')).length)")
          
          echo "csv_count=$CSV_COUNT" >> $GITHUB_OUTPUT
          echo "json_count=$JSON_COUNT" >> $GITHUB_OUTPUT
          
          if [ "$CSV_COUNT" -gt "$JSON_COUNT" ]; then
            echo "needs_migration=true" >> $GITHUB_OUTPUT
            echo "⚠️  CSV has more entries than JSON ($CSV_COUNT vs $JSON_COUNT)"
          else
            echo "needs_migration=false" >> $GITHUB_OUTPUT
            echo "✅ JSON is up to date ($JSON_COUNT entries)"
          fi
          
      - name: Run Incremental Migration
        if: steps.migration_check.outputs.needs_migration == 'true'
        run: |
          cd docs
          node scripts/incremental-migration.js
          
      - name: Validate Migrated Data
        if: steps.migration_check.outputs.needs_migration == 'true'
        run: |
          cd docs
          npm run json:validate
          
      - name: Commit Migration Updates
        if: steps.migration_check.outputs.needs_migration == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if [ -n "$(git diff --name-only)" ]; then
            git add docs/sessions.json
            git add docs/migration.log
            git commit -m "chore: sync CSV to JSON migration [automated]
            
            📊 Migration Sync:
            - CSV entries: ${{ steps.migration_check.outputs.csv_count }}
            - JSON entries: ${{ steps.migration_check.outputs.json_count }}
            - Added new entries to JSON format
            - Validated data integrity
            
            Generated by: CSV to JSON Migration Monitor"
            git push
          fi
          
      - name: Generate Migration Report
        run: |
          cd docs
          echo "# Migration Status Report" > analysis/migration-status.md
          echo "" >> analysis/migration-status.md
          echo "**Date**: $(date)" >> analysis/migration-status.md
          echo "**CSV Entries**: ${{ steps.migration_check.outputs.csv_count }}" >> analysis/migration-status.md
          echo "**JSON Entries**: ${{ steps.migration_check.outputs.json_count }}" >> analysis/migration-status.md
          echo "**Migration Needed**: ${{ steps.migration_check.outputs.needs_migration }}" >> analysis/migration-status.md
          echo "" >> analysis/migration-status.md
          
          if [ -f migration.log ]; then
            echo "## Latest Migration Log" >> analysis/migration-status.md
            echo '\`\`\`json' >> analysis/migration-status.md
            cat migration.log >> analysis/migration-status.md
            echo '\`\`\`' >> analysis/migration-status.md
          fi
