# Remcode workflow version: 0.2.0
# Generated: 2025-05-22T10:44:20.090Z
name: Remcode Scheduled Processing

on:
  push:
    branches: [ main, master, develop ]
  schedule:
    - cron: '0 0 * * 1'
      branches: [ main ]
  workflow_dispatch:
    inputs:
      force_full_reprocess:
        description: 'Force full reprocessing'
        type: boolean
        default: false

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci --legacy-peer-deps

    - name: Process with Remcode
      run: npx remcode@latest process
      env:
        PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_NAME: test-repo
