# Remcode workflow version: 0.2.0
# Generated: 2025-05-22T10:44:20.091Z
name: Remcode Advanced Processing

on:
  push:
    branches: [ main, master, develop ]
  workflow_dispatch:
    inputs:
      force_full_reprocess:
        description: 'Force full reprocessing'
        type: boolean
        default: false
      debug_mode:
        description: 'Enable debug mode'
        type: boolean
        default: false
      embedding_model:
        description: 'Embedding model to use'
        type: string
        default: 'microsoft/graphcodebert-base'
        required: false

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Analyze repository
      id: analyze
      run: npx remcode@latest analyze --output-json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Process with Remcode
      id: process
      run: |
        DEBUG_FLAG=""
        if [ "${{ github.event.inputs.debug_mode }}" == "true" ]; then
          DEBUG_FLAG="--debug"
        fi

        FORCE_FLAG=""
        if [ "${{ github.event.inputs.force_full_reprocess }}" == "true" ]; then
          FORCE_FLAG="--force"
        fi

        EMBEDDING_MODEL="${{ github.event.inputs.embedding_model }}"
        if [ -z "$EMBEDDING_MODEL" ]; then
          EMBEDDING_MODEL="microsoft/graphcodebert-base"
        fi

        npx remcode@latest process $DEBUG_FLAG $FORCE_FLAG --embedding-model="$EMBEDDING_MODEL" --metrics
      env:
        PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_NAME: test-repo

    - name: Upload metrics
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: remcode-metrics
        path: .remcode-metrics.json
        retention-days: 90

    - name: Generate processing report
      if: always()
      run: npx remcode@latest report
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
