name: Session Analytics

on:
  push:
    branches: [main]
    paths: ['docs/SESSIONS.csv']
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Generate session report
      run: |
        cd docs
        node generate-session-report.js
    
    - name: Commit updated reports
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        if git diff --quiet docs/; then
          echo "No changes in session reports"
        else
          git add docs/SESSION_SUMMARY.md docs/session-metrics.json
          git commit -m "chore: Update session analytics

          - Generated SESSION_SUMMARY.md
          - Updated session metrics
          
          Generated by: Session Analytics workflow"
          git push
        fi