name: Session Analytics

on:
  push:
    branches: [main]
    paths: ['sessions/sessions.json']
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight (reduced from every 6 hours)
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'scripts/package-lock.json'
    
    - name: Install dependencies
      working-directory: scripts
      run: npm ci
    
    - name: Generate session report
      working-directory: scripts
      run: npm run session:report
    
    - name: Commit updated reports
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        if git diff --quiet sessions/; then
          echo "No changes in session reports"
        else
          git add sessions/SESSION_SUMMARY.md sessions/session-metrics.json
          git commit -m "chore: Update session analytics

          - Generated SESSION_SUMMARY.md from JSON data
          - Updated session metrics
          
          Generated by: Session Analytics workflow"
          git push
        fi